package Main;

import java.awt.Color;

/**
 *
 * @author tanh2
 */
public class FrameColorsSlider extends javax.swing.JFrame
{
    private int R = 0, G = 0, B = 0;

    /**
     * Creates new form ColorSliderFrame
     */
    public FrameColorsSlider()
    {
        initComponents();
        jLabelRed.setText("朱 = " + jSliderRed.getValue());
        jLabelGreen.setText("緑 = " + jSliderGreen.getValue());
        jLabelBlue.setText("青 = " + jSliderBlue.getValue());
        jLabelColor.setBackground(new Color(jSliderRed.getValue(), jSliderGreen.getValue(), jSliderBlue.getValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelSpecs = new javax.swing.JPanel();
        jSliderRed = new javax.swing.JSlider();
        jSliderGreen = new javax.swing.JSlider();
        jSliderBlue = new javax.swing.JSlider();
        jLabelRed = new javax.swing.JLabel();
        jLabelGreen = new javax.swing.JLabel();
        jLabelBlue = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colors Slider");
        setBackground(new java.awt.Color(255, 255, 255));

        jSliderRed.setMaximum(255);
        jSliderRed.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSliderRedStateChanged(evt);
            }
        });

        jSliderGreen.setMaximum(255);
        jSliderGreen.setValue(0);
        jSliderGreen.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSliderGreenStateChanged(evt);
            }
        });

        jSliderBlue.setMaximum(255);
        jSliderBlue.setValue(0);
        jSliderBlue.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSliderBlueStateChanged(evt);
            }
        });

        jLabelRed.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabelRed.setForeground(new java.awt.Color(255, 0, 0));
        jLabelRed.setText("朱 = 0");

        jLabelGreen.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabelGreen.setForeground(new java.awt.Color(0, 255, 0));
        jLabelGreen.setText("緑 = 0");

        jLabelBlue.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jLabelBlue.setForeground(new java.awt.Color(0, 0, 255));
        jLabelBlue.setText("青 = 0");

        javax.swing.GroupLayout jPanelSpecsLayout = new javax.swing.GroupLayout(jPanelSpecs);
        jPanelSpecs.setLayout(jPanelSpecsLayout);
        jPanelSpecsLayout.setHorizontalGroup(
            jPanelSpecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSpecsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSpecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSpecsLayout.createSequentialGroup()
                        .addComponent(jSliderRed, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelRed, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addGroup(jPanelSpecsLayout.createSequentialGroup()
                        .addComponent(jSliderBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelSpecsLayout.createSequentialGroup()
                        .addComponent(jSliderGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelGreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSpecsLayout.setVerticalGroup(
            jPanelSpecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSpecsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSpecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSliderRed, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSpecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSliderGreen, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelGreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSpecsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSliderBlue, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabelBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelColor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelColor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSpecs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelSpecs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderRedStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderRedStateChanged
    {//GEN-HEADEREND:event_jSliderRedStateChanged
        Color result = new Color(R, G, B);
        R = jSliderRed.getValue();
        jLabelRed.setText("朱 = " + R);
        jLabelColor.setBackground(result);
    }//GEN-LAST:event_jSliderRedStateChanged

    private void jSliderGreenStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderGreenStateChanged
    {//GEN-HEADEREND:event_jSliderGreenStateChanged
        Color result = new Color(R, G, B);
        G = jSliderGreen.getValue();
        jLabelGreen.setText("緑 = " + G);
        jLabelColor.setBackground(result);
    }//GEN-LAST:event_jSliderGreenStateChanged

    private void jSliderBlueStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSliderBlueStateChanged
    {//GEN-HEADEREND:event_jSliderBlueStateChanged
        Color result = new Color(R, G, B);
        B = jSliderBlue.getValue();
        jLabelBlue.setText("青 = " + B);
        jLabelColor.setBackground(result);
    }//GEN-LAST:event_jSliderBlueStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Windows".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrameColorsSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrameColorsSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrameColorsSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrameColorsSlider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrameColorsSlider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBlue;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelGreen;
    private javax.swing.JLabel jLabelRed;
    private javax.swing.JPanel jPanelSpecs;
    private javax.swing.JSlider jSliderBlue;
    private javax.swing.JSlider jSliderGreen;
    private javax.swing.JSlider jSliderRed;
    // End of variables declaration//GEN-END:variables
}
